project:
  name: Michelle Winder
  description: ''
  tools: []
  current_focus: 'testing the hub - hi'
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: pauldingus
    contributors: []
  campaign:
    candidate: Michelle Winder
    office: Texas State House District 99
  auto_refresh: true
